spring.application.name=Lakshya server

# Server configuration
server.port=8080

# Database configuration
# Using postgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/lakshya_db
#spring.datasource.username=postgres
#spring.datasource.password=Yuvaraj@1
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.url=jdbc:postgresql://interchange.proxy.rlwy.net:49860/railway
spring.datasource.username=postgres
spring.datasource.password=jOrJmfCRyKlidMKuSHEQPuAzQqfRwtNq
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'



# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.lakshya=DEBUG


# RAZORPAY configuration
razorpay.key-id=rzp_live_SISv2snevTBZgn
razorpay.key-secret=LCWoRIwuh1Ui04psGQNd6Fx1

# RAZORPAY TEST configuration
# razorpay.key-id=rzp_test_SIUKjBGqvysaXO
# razorpay.key-secret=uYIG7UKLz1SmlKbd1itCEwE7

# Spring Security configuration
spring.security.user.name=Yuvaraj
spring.security.user.password=Yuvaraj@0402
spring.security.user.roles=ADMIN

# JWT Configuration
jwt.secret=JWTTokenGeneration256BitsLongForHS256Algorithm
jwt.expiration=86400000

# Refresh Token Configuration (7 days in milliseconds)
jwt.refresh-expiration=604800000






